# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM node:lts-alpine AS builder
WORKDIR /app
# Copy package and config
COPY package.json package-lock.json tsconfig.json ./
# Copy source files
COPY src ./src
# Install dependencies (skip lifecycle scripts) and build
RUN npm install --ignore-scripts && npm run build

FROM node:lts-alpine
WORKDIR /app
# Copy built files and dependencies
COPY --from=builder /app/build ./build
COPY --from=builder /app/node_modules ./node_modules

# Run as non-root user
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser

# Default command
ENTRYPOINT ["node", "build/index.js"]
